Database Implementation Techniques Programming Task SoSe2015: unittest.cpp File Reference
unittest.cpp File Reference
#include <string>
#include <core/global_definitions.hpp>
#include <core/base_column.hpp>
#include <core/column_base_typed.hpp>
#include <core/column.hpp>
#include <core/compressed_column.hpp>
#include <compression/dictionary_compressed_column.hpp>
Functions
template<typename T >
const T get_rand_value ()
template<>
const int get_rand_value ()
template<>
const float get_rand_value ()
template<>
const std::string get_rand_value ()
template<class T >
void fill_column (boost::shared_ptr< ColumnBaseTyped< T >> col, std::vector< T > &reference_data)
template<class T >
bool equals (std::vector< T > reference_data, boost::shared_ptr< ColumnBaseTyped< T > > col)
template<class T >
bool test_column (boost::shared_ptr< ColumnBaseTyped< T >> col, std::vector< T > &reference_data)
bool unittest (boost::shared_ptr< ColumnBaseTyped< int >> col)
bool unittest (boost::shared_ptr< ColumnBaseTyped< float >> col)
bool unittest (boost::shared_ptr< ColumnBaseTyped< std::string >> col)
Function Documentation
template<class T > bool equals (std::vector< T > reference_data, boost::shared_ptr< ColumnBaseTyped< T > > col)
Definition at line 51 of file unittest.cpp.
Referenced by test_column().
template<class T > void fill_column (boost::shared_ptr< ColumnBaseTyped< T >> col, std::vector< T > & reference_data)
Definition at line 39 of file unittest.cpp.
Referenced by unittest().
template<typename T > const T get_rand_value ()
Definition at line 13 of file unittest.cpp.
template<> const int get_rand_value ()
Definition at line 18 of file unittest.cpp.
template<> const float get_rand_value ()
Definition at line 23 of file unittest.cpp.
template<> const std::string get_rand_value ()
Definition at line 28 of file unittest.cpp.
template<class T > bool test_column (boost::shared_ptr< ColumnBaseTyped< T >> col, std::vector< T > & reference_data)
Definition at line 68 of file unittest.cpp.
References equals().
Referenced by unittest().
bool unittest (boost::shared_ptr< ColumnBaseTyped< int >> col)
Definition at line 157 of file unittest.cpp.
References fill_column(), and test_column().
bool unittest (boost::shared_ptr< ColumnBaseTyped< float >> col)
Definition at line 166 of file unittest.cpp.
References fill_column(), and test_column().
bool unittest (boost::shared_ptr< ColumnBaseTyped< std::string >> col)
Definition at line 175 of file unittest.cpp.
References fill_column(), and test_column().